install.packages("lubridate")
install.packages("dplyr")

library(dplyr)
library(lubridate)
library(tidyverse)

meals <- read.csv("/Users/hh/Documents/Pratt/Data_Analytics/info640/DataSets/mealplan.csv", skip=3, header=TRUE, check.names = FALSE)
class(meals)
dim(meals)
names(meals)
str(meals)
glimpse(meals)
summary(meals)
head(meals)
tail(meals)
meals1 <- gather(meals, date, value, -Meal, -Location)
head(meals1)
meals1 <- separate(meals1, value, c('entree', 'price'), sep=',')
head(meals1)
str(meals1)
meals1$date <- mdy(meals1$date)
